export const LEGAL_SPECIALTIES = [
  'Direito Civil',
  'Direito Penal',
  'Direito Trabalhista',
  'Direito de Família',
  'Direito do Consumidor',
  'Direito Tributário',
  'Direito Previdenciário',
  'Direito Administrativo',
  'Direito Empresarial / Comercial',
  'Direito Imobiliário',
  'Direito Ambiental',
  'Direito Digital e Tecnologia',
  'Direito Internacional',
  'Direito Eleitoral',
  'Direito Constitucional',
  'Direito Bancário',
  'Direito de Trânsito',
  'Direito Médico e da Saúde',
  'Direito Agrário',
  'Direito Sucessório / Inventário',
  'Direito Contratual',
  'Recuperação de Crédito',
  'Outro',
]
